version: '3'

services:
  postgres:
    image: 'postgres:14.3-alpine'
    container_name: lab6-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lab6
    restart: unless-stopped

  app:
    image: 'ivanxc/book-shop:0.0.1'
    container_name: lab6-app
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=lab6
    restart: "on-failure"

volumes:
  postgres-data: